### ISSUE TITLE
Add badges for readme using npm-badger

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/search-a-tags#11]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/search-a-tags`
3. Go to root directory `cd search-a-tags`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by AryanAg08** [comment]
hii, I would like to work on this project

**Comment by arshadkazmi42** [comment]
Sure go ahead

**Comment by AryanAg08** [comment]
Done you can check it out and merge my pr 🙂

**Comment by arshadkazmi42** [comment]
Fixed in #15
